Issue 122 timewarp
ILLIXR/ILLIXR pull request #155
Opened 2020-10-05 02:57 UTC by charmoniumQ

2020-10-28 22:52 UTC, mhuzai reviewed
If you can fix the compilation error and update with master, this is good to go.

Btw, moving the logging to before the GL querying saves a little bit of the CPU time you spend spinning on the query. Nice!

2020-10-28 22:52 UTC, mhuzai commented on timewarp_gl/plugin.cpp
> +		printf("\033[1;36m[TIMEWARP]\033[0m Motion-to-display latency: %3f ms\n", float(mtp.count()) / 1e6);
There is a compilation error here. `mpt.count()` should be `imu_to_display.count()`.

Also, we print both MTP and PTD. Might as well print RTD too.

2020-10-29 18:28 UTC, mhuzai requested changes
Please print this as well: `printf("\033[1;36m[TIMEWARP]\033[0m Render-to-display latency: %3f ms\n", float(render_to_display.count()) / 1e6);`

2020-10-29 21:45 UTC, mhuzai approved these changes

2020-10-30 01:04 UTC, apache8080 approved these changes

2020-11-03 00:30 UTC, merged