Issue 196: Updated imu_camp_type to have depth images
ILLIXR/ILLIXR pull request #197
Opened 2020-11-17 19:17 UTC by apache8080

Closes #196

2020-11-18 00:56 UTC, apache8080 commented
After discussing with @mhuzai, I am going to change the way we pass sensor data by having different types/topics for each sensor type (e.g: imu_type for imu data, stereo_gray_type for stereo grayscale images)

2020-11-18 01:01 UTC, charmoniumQ submitted a review, later dismissed

2020-11-18 21:47 UTC, charmoniumQ commented on common/data_format.hpp
> +	typedef unsigned long long
This looks like a mistake. Missing a semicolon and a typename (such as ullong)?

2020-12-02 18:32 UTC, e3m3 requested changes
Looks good other than the issue @charmoniumQ pointed out, and the provided formatting suggestion

2020-12-02 18:32 UTC, e3m3 commented on offline_imu_cam/plugin.cpp
> +			cam1
```suggestion
			cam1,
```

2020-12-02 18:32 UTC, e3m3 commented on realsense/plugin.cpp
> +                    std::optional<cv::Mat *> depth_img = std::nullopt;
```suggestion
                    std::optional<cv::Mat *> rgb_img0 = std::nullopt;
                    // Realsense only has rgb image for left image so rgb_img1 will always be null
                    std::optional<cv::Mat *> rgb_img1 = std::nullopt;
                    std::optional<cv::Mat *> depth_img = std::nullopt;
```

2020-12-02 18:32 UTC, e3m3 commented on realsense/plugin.cpp
> +                        depth_img = cam_type_.depth;
```suggestion
                        gb_img0 = cam_type_rgb_img0;
                        depth_img = cam_type_.depth;
```

2020-12-02 18:32 UTC, e3m3 commented on zed/src/main.cpp
> +	cv::Mat* rgb_img1;
```suggestion
    cv::Mat* rgb_img0;
    cv::Mat* rgb_img1;
```

2020-12-02 18:32 UTC, e3m3 commented on zed/src/main.cpp
> +		rgbR_ocv = slMat2cvMat(rgbR_zed);
```suggestion
       rgbL_ocv = slMat2cvMat(rgbL_zed);
       rgbR_ocv = slMat2cvMat(rgbR_zed);
```

2020-12-02 18:32 UTC, e3m3 commented on zed/src/main.cpp
> +	Mat rgbR_zed;
```suggestion
    Mat rgbL_zed;
    Mat rgbR_zed;
```

2020-12-02 18:32 UTC, e3m3 commented on zed/src/main.cpp
> +	cv::Mat rgbR_ocv;
```suggestion
    cv::Mat rgbL_ocv;
    cv::Mat rgbR_ocv;
```

2020-12-02 18:32 UTC, e3m3 commented on zed/src/main.cpp
> +		zedm->retrieveImage(rgbR_zed, VIEW::RIGHT, MEM::CPU, image_size);
```suggestion
        zedm->retrieveImage(rgbL_zed, VIEW::LEFT, MEM::CPU, image_size);
        zedm->retrieveImage(rgbR_zed, VIEW::RIGHT, MEM::CPU, image_size);
```

2020-12-02 18:32 UTC, e3m3 commented on zed/src/main.cpp
> +		std::optional<cv::Mat*> depth_img = std::nullopt;
```suggestion
        std::optional<cv::Mat*> rgb_img0 = std::nullopt;
        std::optional<cv::Mat*> rgb_img1 = std::nullopt;
        std::optional<cv::Mat*> depth_img = std::nullopt;
```

2020-12-02 18:32 UTC, e3m3 commented on zed/src/main.cpp
> +            depth_img = c->depth;
```suggestion
            gb_img0 = c->rgb_img0;
            rgb_img1 = c->rgb_img1;
            depth_img = c->depth;
```

2020-12-02 18:32 UTC, e3m3 commented on zed/src/main.cpp
>          });
```suggestion
                imu_time_point,
                av,
                la,
                img0,
                img1,
                rgb_img0,
                rgb_img1,
                depth_img,
                imu_time,
        });
```

2021-04-24 22:54 UTC, mhuzai commented
This is quite out-of-date now, and should get tackled afresh in preparation for the interfaces working group.

2021-04-24 22:54 UTC, closed without merging