Revert boost install script
ILLIXR/ILLIXR pull request #323
Opened 2022-02-16 23:49 UTC by mhuzai

This reverts commit 8590c7422c9e0e72d11df0717cee201a12cb00d0.
We do not need to build boost ourselves, the one from apt works just fine.

2022-02-18 22:14 UTC, JeffreyZh4ng approved these changes

2022-02-18 22:15 UTC, shg8 requested changes
I think we also need to comment out the prompt_install commands in install_deps.sh

2022-02-18 22:46 UTC, mhuzai commented
> I think we also need to comment out the prompt_install commands in install_deps.sh

Good catch! How on earth was this even working before the commit that I reverted got pushed? :confused:

2022-02-19 07:31 UTC, charmoniumQ approved these changes

2022-02-20 20:55 UTC, merged