Adding hand tracking plugin
ILLIXR/ILLIXR pull request #428
Opened 2024-10-30 02:13 UTC by astro-friedel

This PR introduces a hand tracking plugin to ILLIXR.

Inputs:

Outputs:

Dependencies:

Other changes made:
switchboard now handles all environment variables and stores them in a map
opencv_data_types were modified to all inherit from a common base. This allows for a plugin to be able to subscribe to any number of image streams with the same function.

2025-02-05 18:14 UTC, rsingh76 commented on include/illixr/data_format/camera_data.hpp
It is mentioned in the PR document, but will be helpful to add high-level comments at the beginning of this file about why these structs are needed?

2025-02-05 18:14 UTC, rsingh76 commented on include/illixr/data_format/coordinate.hpp
Is this Zed specific, if so, please mention.

2025-02-05 18:16 UTC, rsingh76 commented on include/illixr/data_format/misc.hpp
> +struct [[maybe_unused]] connection_signal : public switchboard::event {
Comments here

2025-02-05 18:18 UTC, rsingh76 commented on include/illixr/data_format/point.hpp
Some high-level comments about points, points_with_units, and other new structs will be helpful.

2025-02-05 18:30 UTC, rsingh76 commented on include/illixr/math_util.hpp
> +    const Eigen::Matrix3f conversion[6][6] = {
Better name? or perhaps more descriptive comments?

2025-02-05 18:35 UTC, rsingh76 commented on include/illixr/math_util.hpp
> +     * Rotation matrix for a point tp rotate its axes to convert it to a new coordinate system
Please correct me if I am wrong, but is this for converting Euler angles to a Rotation matrix? If yes, then mention Euler angles. Current comments about the coordinate system might confuse some users.

2025-02-05 18:52 UTC, rsingh76 commented on plugins/hand_tracking/viewer/plugin.cpp
> +constexpr float convert[5][5] = {
Why not have this in the data_fromat/units.hpp?

2025-02-05 20:09 UTC, sriramdvt requested changes
Added some comments requesting documentation, reuse of existing definitions instead of new ones, and a few clarifications.

I was able to run the hand tracking plugin with a Zed. I can confirm that the overlay of the hand points on the hands works well. I cannot confirm if the coordinates (X,Y,Z) are accurate just yet. Do you have any suggestions about how those can be checked?

2025-02-05 20:09 UTC, sriramdvt commented on scripts/mediapipe_tool_wrapper.py
Can this file be briefly commented at the beginning? Looks like this script is to have a look at all the files that a Bazel build system would have. Just writing that briefly at the top should be fine.

2025-02-05 20:14 UTC, sriramdvt commented on include/illixr/data_format/point.hpp
> +    void check_validity() {
I see that this is used in the `hand_tracking` plugin, but there are no `asserts` or return values from this function. Not sure what this is doing.

2025-02-05 21:15 UTC, rsingh76 commented on docs/docs/plugin_README/README_hand_tracking.md
> +    - **z**: z-coordinate (not an absolute distance, but a measure of the point's depth relative to other points)
Also add why do we want to use relative depth, and not metric depth. I assume we get metric depth from the Zed?

2025-02-05 21:19 UTC, rsingh76 commented on scripts/mediapipe_tool_wrapper.py
I am not sure about the purpose of this code, can you add some documentation?

2025-02-05 21:19 UTC, rsingh76 commented on profiles/test.yaml
Perhaps rename this file to something else?

2025-02-05 22:51 UTC, astro-friedel commented on include/illixr/data_format/camera_data.hpp
Done

2025-02-05 22:53 UTC, astro-friedel commented on include/illixr/data_format/coordinate.hpp
It is not zed specific, but I did adopt their naming convention.

2025-02-05 22:55 UTC, astro-friedel commented on include/illixr/data_format/misc.hpp
> +struct [[maybe_unused]] connection_signal : public switchboard::event {
I do not know exactly what these are. These are the structs from the original data_format.hpp that did not fall into specific categories. All comments were moved with them.

2025-02-06 01:11 UTC, astro-friedel commented on include/illixr/data_format/point.hpp
done

2025-02-06 01:15 UTC, astro-friedel commented on include/illixr/math_util.hpp
> +    const Eigen::Matrix3f conversion[6][6] = {
done

2025-02-06 01:17 UTC, astro-friedel commented on include/illixr/math_util.hpp
> +     * Rotation matrix for a point tp rotate its axes to convert it to a new coordinate system
updated documentation, it is mean for converting a point from one coordinate reference frame to another

2025-02-06 01:20 UTC, astro-friedel commented on plugins/hand_tracking/viewer/plugin.cpp
> +constexpr float convert[5][5] = {
fixed

2025-02-06 01:24 UTC, astro-friedel commented on docs/docs/adding_mediapipe.md
> +with this hany online [tool][16]
it was a typo

2025-02-06 01:24 UTC, astro-friedel commented on docs/docs/modifying_a_plugin.md
> +        :::bash
yes, it is how to indicate a code block and language to mkdocs

2025-02-06 01:55 UTC, astro-friedel commented on docs/docs/plugin_README/README_hand_tracking.md
> +    - **z**: z-coordinate (not an absolute distance, but a measure of the point's depth relative to other points)
I added some clarification

2025-02-06 01:56 UTC, astro-friedel commented on docs/docs/plugin_README/README_hand_tracking.md
> +The plugin published an `ht_frame` which contains the following data
this was also clarified

2025-02-06 01:59 UTC, astro-friedel commented on include/illixr/data_format/hand_tracking_data.hpp
> +                // TODO: something
fixed

2025-02-06 01:59 UTC, astro-friedel commented on include/illixr/data_format/point.hpp
> +    bool                          fixed = false;
already done

2025-02-06 02:01 UTC, astro-friedel commented on include/illixr/data_format/point.hpp
> +    void check_validity() {
It is setting the internal validity flag for the object based on the values of the contained points. If there are any valid points then this flag is set to true

2025-02-06 02:06 UTC, astro-friedel commented on include/illixr/data_format/pose.hpp
> +struct [[maybe_unused]] pose_data {
I added some documentation

2025-02-06 02:08 UTC, astro-friedel commented on include/illixr/data_format/pose.hpp
I added documentation to the ones I used

2025-02-06 02:11 UTC, astro-friedel commented on plugins/fauxpose/plugin.cpp
> +using namespace ILLIXR::data_format;
I believe so, there is a usage of pose_type on line 120 that have no namespacing

2025-02-06 02:13 UTC, astro-friedel commented on plugins/hand_tracking/viewer/plugin.cpp
> +std::ofstream out_data("/home/friedel/devel/ILLIXR/points.dat", std::ios_base::out | std::ios_base::trunc);
removed, no longer needed

2025-02-06 02:16 UTC, astro-friedel commented on plugins/zed/zed_camera.hpp
> +        const auto temp = initial_position_.getTranslation();
That question may be best answered by the group. I wonder why that version of gcc throws an error. It is not an issue so I removed them

2025-02-06 02:20 UTC, astro-friedel commented on scripts/mediapipe_tool_wrapper.py
this script was not meant to be in there, it is not ready for others to use yet.

2025-02-06 02:20 UTC, astro-friedel commented on docs/docs/plugin_README/README_hand_tracking.md
> +    - **z**: z-coordinate (not an absolute distance, but a measure of the point's depth relative to other points)
The relative depth is what we get from mediapipe, this is the data structure we get from that.

2025-02-06 02:21 UTC, astro-friedel commented on scripts/mediapipe_tool_wrapper.py
I removed the script, it is not ready for general use

2025-02-06 02:23 UTC, astro-friedel commented on profiles/test.yaml
done

2025-02-06 03:54 UTC, rsingh76 approved these changes

2025-02-06 17:36 UTC, sriramdvt approved these changes
LGTM

2025-02-17 19:55 UTC, rsingh76 commented on include/illixr/data_format/frame.hpp
I don't understand this change.
Can you add some more detailed comments?

2025-02-17 21:50 UTC, sriramdvt commented on include/illixr/data_format/point.hpp
I think the auto-formatter split up the comments into multiple lines. Can that be overwritten to keep them in the same line?

2025-02-17 21:54 UTC, astro-friedel commented on include/illixr/data_format/frame.hpp
I am not sure, but if I ventured a guess, there was some trailing white space that got trimmed off

2025-02-17 21:56 UTC, astro-friedel commented on include/illixr/data_format/frame.hpp
Ah, I was incorrect. The view that github gives is incorrect. There were a few lines added below the pragma line:


#ifdef Success
    #undef Success // For 'Success' conflict
#endif

2025-02-17 22:53 UTC, sriramdvt commented on profiles/all.yaml
>  visualizers: openvins
For all the profiles, I remember that the "visualizers" field was removed in the hand tracking branch. Is it showing up here because the main branch has this field?

2025-02-17 23:03 UTC, astro-friedel commented on profiles/all.yaml
>  visualizers: openvins
Yes. It will be formally removed in another PR

2025-02-18 01:03 UTC, rsingh76 approved these changes

2025-02-19 14:07 UTC, sriramdvt approved these changes

2025-02-19 14:35 UTC, merged